### PR TITLE
Refactor/optional unicodeplots

### PR DESCRIPTION
**Pull request by xamberl**

### CODE REVIEW

**Comment by brainandforce** [comment]
I just rebased this commit on the current `main` branch. At the moment, it seems like the UnicodePlots integration is broken because `__init__()` was declared with three underscores instead of two. This should fix it.

**Comment by xamberl** [comment]
I'm actually thinking about removing UnicodePlots since installing and loading it is relatively slow with only marginal quality-of-life improvement. I trust that users of DFT-raMO know how to construct a plot from data in a txt file. What do you think, @brainandforce?

**Comment by brainandforce** [comment]
To mirror what I said at our meeting: I think the UnicodePlots optional dependency can stay provided that loading it doesn't significantly decrease the performance of the package in non-interactive scenarios.

**Comment by xamberl** [comment]
Alright, I'll leave it in for now and close the branch. Thanks!

**Pull request merged**
